### ISSUE TITLE
UNESCO omission of sexual orientation and gender identity

### ISSUE THREAD

**Issue by bbcjamesfletcher** [webmachinelearning/ethical-webmachinelearning#15]
@michael-n-cooper (@anssiko I don't seem to be able to tag anyone apart from you and Dom in these - can you tag Michael?)

I'm working through the output of the brainstorming session and seen your comment:

"The UN guidance loudly omits topics like sexual orientation and gender identity / expression; those, along with disability status, form “cultural groups” that may not be recognized as important to the design of ML, yet are as important to success as respectiing people’s ethnic background, language, religion, national political situation…"

This is true and i'm wondering how best to deal with it. Our document doesn't import all the language of the UNESCO doc, and I think we should work on the basis that our doc is "based on" UNESCO but separate and stands on its own. A few ideas:

1) I'd propose that where there are general statements about fairness, diversity, non-discrimination etc., we shouldn't call out any specific characteristics or groups to compensate for the problems you identify with UNESCO.

So the guidance for Fairness and Non-discrimination says "The benefits of ML systems should be available and accessible to all. ML actors should minimize and avoid reinforcing or perpetuating bias and discrimination, particularly against vulnerable and historically marginalised groups."

As this doesn't identify any particular groups, I feel it can be interpreted broadly, and adding any specific ones either creates a long list which will inevitably omit someone, or begs the question of why specific groups are called out.

2) But this does raise the question of whether there should be a statement somewhere, perhaps at the beginning of S4 where UNESCO is introduced, or Appendix 2 which goes into further detail about why UNESCO was chosen, along the lines of your comment above to explicitly call out the omission in UNESCO and make clear that we consider sexual orientation and gender identity to be included in protected characteristics.

3) I think that where specific characteristics are spelled out as being protected, we should ensure they are appropriately inclusive.

So Value 3 "Ensuring Diversity and Inclusiveness" refers to "enabling the active participation of all individuals or groups, regardless of lifestyle choices, beliefs, opinions, expressions or personal experiences" but does not refer to "identity". In this case I would propose adding "identity" to the list.

Would appreciate your thoughts on all of these.

**Comment by anssiko** [comment]
(Just noting here @bbcjamesfletcher managed to tag @michael-n-cooper properly in his GitHub comment 👍 However, there's a technical limitation [or feature...] that prevents using the "Assignees" or "Reviewers" side pane for people outside a particular GitHub organization. In such cases it is fine to just @ tag the person in the comments as was done here.)

**Comment by michael-n-cooper** [comment]
I come at my comments from a couple opposing perspectives:

- As a technical writer, I favour broad inclusive language that is less likely to omit anyone, and does not differentially privilege particular groups by mentioning them, with others relegated to an "etcetera".
- As an advocate, I find that groups which are not explicitly mentioned tend to be overlooked, sometimes from simple lack of awareness.

Speaking from the first perspective, I support broad language, particularly in major statements of principle.

But because machine learning requires active inclusion to avoid developing unexpected biases, we cannot rest just on general principles. People using the ethics document need to know what groups to include or consider. While that's really an operational question, I feel that at least the ethics document should reflect W3C's stated non-discrimination values. I find a statement of them in the [CEPC](https://www.w3.org/Consortium/cepc/#unacceptablebehavior): "gender, gender identity and gender expression, sexual orientation, disability (both visible and invisible), mental health, neurotype, physical appearance, body, age, race, socio-economic status, ethnicity, caste, nationality, language, or religion" (although that list is in a bullet specific to offensive comments, I think it is general for W3C).

I think the Operationalization section of the document will need to address bias very directly. Unless we find another reference that feels sufficiently comprehensive (which I didn't find on quick search), I think at least we need to provide some guidance ourselves. For bias, we should recommend steps like actively considering groups to include in training, and building robust procedures to detect and fix emerging unexpected bias into the development process. I think W3C's list of groups perhaps might go here, if it doesn't find a home in the Fairness and non-discrimination section. 

Because bias is contextual, no list of protected groups can be complete. It might be important to provide or reference guidance on identifying groups disenfranchised in a particular context, so they can be actively included as well. It might also be important to indicate that it is important to actively avoid machine learning bias against groups, regardless of the values of the power group for its context.

**Comment by bbcjamesfletcher** [comment]
@michael-n-cooper thanks for this, and in particular for the CEPC reference. That is useful - I agree that "the ethics document should reflect W3C's stated non-discrimination values". I think the best place to include them is in the fairness section - that feels like the right place to be explicit about the characteristics. Having it there then sets the expectation / ambit for more general references elsewhere in the doc. I will add. 

As flagged in my OP, I will also add 'identity' to the characteristics for Value 3 "Ensuring Diversity and Inclusiveness".

**Comment by anssiko** [comment]
Addressed by #19.
